Retry getting bootnodes for a minute

diff --git a/geth-miner.deployment.yaml b/geth-miner.deployment.yaml
--- a/geth-miner.deployment.yaml
+++ b/geth-miner.deployment.yaml
@@ -20,8 +20,10 @@ spec:
         command: ["/bin/sh"]
         args: 
         - "-c"
-        - "geth --bootnodes=`cat /root/.ethereum/bootnodes` --mine --etherbase=0 --networkid=${NETWORK_ID} --ethstats=${HOSTNAME}:${ETHSTATS_SECRET}@ethstats-service.default --verbosity=5"
+        - "geth --bootnodes=`cat /root/.ethereum/bootnodes` --mine --etherbase=0 --networkid=${NETWORK_ID} --ethstats=${HOSTNAME}:${ETHSTATS_SECRET}@${ETHSTATS_SVC} --verbosity=5"
         env:
+        - name: ETHSTATS_SVC
+          value: ethstats-service.default 
         - name: ETHSTATS_SECRET
           valueFrom:
             secretKeyRef:
@@ -75,19 +77,25 @@ spec:
         - |-
           apk add --no-cache curl; 
           CNT=0;
-          while [ $CNT -le 30 ] 
+          while [ $CNT -le 60 ] 
           do
-            curl -s bootnode-registrar-service.default | xargs echo -n >> /geth/bootnodes;
+            curl -s $BOOTNODE_REGISTRAR_SVC | xargs echo -n >> /geth/bootnodes;
             if [ -s /geth/bootnodes ] 
             then
+              echo "DONE.";
+              cat /geth/bootnodes;
               exit 0;
             fi;
 
-            echo "no bootnodes found. retrying $CNT..."; 
-            sleep 1 || break;
+            echo "no bootnodes found from bootnode-registrar. retrying $CNT..."; 
+            sleep 2 || break;
             CNT=$((CNT+1));
           done;
-          exit 1;
+          echo "WARNING. unable to find bootnodes. continuing but geth may not be able to find any peers.";
+          exit 0;
+        env:
+        - name: BOOTNODE_REGISTRAR_SVC
+          value: bootnode-registrar-service.default
         volumeMounts:
         - name: data
           mountPath: /geth
diff --git a/geth-tx.deployment.yaml b/geth-tx.deployment.yaml
--- a/geth-tx.deployment.yaml
+++ b/geth-tx.deployment.yaml
@@ -5,7 +5,7 @@ metadata:
   labels:
     app: geth-tx
 spec:
-  replicas: 3
+  replicas: 2
   selector:
     matchLabels:
       app: geth-tx
@@ -20,8 +20,10 @@ spec:
         command: ["/bin/sh"]
         args: 
         - "-c"
-        - "geth --bootnodes=`cat /root/.ethereum/bootnodes` --rpc --rpcapi=eth,net,web3 --rpccorsdomain='*' --ws --networkid=${NETWORK_ID} --ethstats=${HOSTNAME}:${ETHSTATS_SECRET}@ethstats-service.default --verbosity=5"
+        - "geth --bootnodes=`cat /root/.ethereum/bootnodes` --rpc --rpcapi=eth,net,web3 --rpccorsdomain='*' --ws --networkid=${NETWORK_ID} --ethstats=${HOSTNAME}:${ETHSTATS_SECRET}@${ETHSTATS_SVC} --verbosity=5"
         env:
+        - name: ETHSTATS_SVC
+          value: ethstats-service.default 
         - name: ETHSTATS_SECRET
           valueFrom:
             secretKeyRef:
@@ -61,10 +63,31 @@ spec:
         command: ["/bin/sh"]
         args:
         - "-c"
-        - "apk add --no-cache curl && curl -v -o /root/.ethereum/bootnodes bootnode-registrar-service.default"
+        - |-
+          apk add --no-cache curl; 
+          CNT=0;
+          while [ $CNT -le 60 ] 
+          do
+            curl -s $BOOTNODE_REGISTRAR_SVC | xargs echo -n >> /geth/bootnodes;
+            if [ -s /geth/bootnodes ] 
+            then
+              echo "DONE.";
+              cat /geth/bootnodes;
+              exit 0;
+            fi;
+
+            echo "no bootnodes found from bootnode-registrar. retrying $CNT..."; 
+            sleep 2 || break;
+            CNT=$((CNT+1));
+          done;
+          echo "WARNING. unable to find bootnodes. continuing but geth may not be able to find any peers.";
+          exit 0;
+        env:
+        - name: BOOTNODE_REGISTRAR_SVC
+          value: bootnode-registrar-service.default
         volumeMounts:
         - name: data
-          mountPath: /root/.ethereum
+          mountPath: /geth
       volumes:
       - name: data
         emptyDir: {}
